# Generated by Django 5.1 on 2024-08-30 20:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0002_person_remove_choice_votes_answer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="choice",
            name="question",
        ),
    ]
