# Generated by Django 5.1 on 2024-09-02 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0003_remove_choice_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="polls.question",
            ),
            preserve_default=False,
        ),
    ]
